RecMedia = RecMedia or {}

RecMedia["54866236-1842-4f75-a94e-c0bf91051f5e"] = {
	itemDisplayName = "VHS: Quo",
	title = "Ueber Quo und die Sakura",
	subtitle = nil,
	author = nil,
	extra = nil,
	spawning = 99,
	category = "Jazzy-VHS",
	lines = {
		{ text = "*Das Bild zeigt einen leeren Stuhl*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "*James laeuft von der Kamera zum Stuhl und setzt sich*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Wenn ihr das seht, bin ich wohl nicht mehr am Leben.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Dieses Video soll meine Geschichte bewahren, falls ich es nicht geschafft habe.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Am 5. Dezember 1994 begann meine Suche in Chicago.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Dort hoffte ich, meine Mutter Mary zu finden.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Es war der letzte Ort, an dem sie gewesen sein koennte.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Doch ich traf nicht Mary, sondern andere Ueberlebende.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Sie wurden von einem Mann namens Lucas angefuehrt.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Chicago war ueberrannt von schnelleren und staerkeren Zombies.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Sie hielten stand, weil sie sich in einer U-Bahn-Station verbarrikadiert hatten.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Diese Kreaturen kamen aus dem Norden und ziehen langsam in den Sueden.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "In wenigen Monaten wuerden sie auch Knox County erreichen.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James amtet durch*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Im Lager traf ich einen Mann namens Itsuki.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Er war ein brillanter Kopf, ein Computergenie aus Japan.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Itsuki hatte sich mit Wissenschaftlern vernetzt, um die Apokalypse zu verstehen.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Sie suchten nach einer Loesung und der Ursache des Virus.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Um ihre Forschung geheim zu halten, hatte er eine Gruppe gegruendet: Sakura.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Das Militaer durfte nichts erfahren, weil es vermutlich selbst hinter dem Virus steckte.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Ich erzaehlte vom Homo Superior Orden ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... welcher von Prof. Dr. Dr. Dr. von Adelhart geleitet wurde.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Adelhart forschte selbst an diesem toedlichen Zombie-Virus.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Ich erzaehlte Itsuki, was ich ueber Adelhart und die Forschungen erfahren hatte.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Sie wollten mehr darueber erfahren und fragten mich ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... ob ich mich der Sakura Gruppe anschliessen wolle.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Sie wollten, dass ich einen Alter-Ego erschaffe.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Ich nannte mich Quo und wurde einer von ihnen.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James atmet durch*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Die andere Sakura-Mitglieder heissen ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Itsuki Yamada", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Claire Harper", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Hiroshi Nakamura", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "und Ryan Gates.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James atmet durch*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Nach Adelharts Tod schaffte ich es mit Itsukis Hilfe ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... die Systeme des Ordens mit denen von Sakura zu verbinden.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Ich hoffe, Knox County ist auf das vorbereitet, was kommt.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Die Bedrohung aus dem Norden wird nicht aufzuhalten sein.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Ihr muesst stark und vereint sein, um zu ueberleben.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Viel Glueck!", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James Zimmermann steht auf und laeuft zur Kamera*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "*Das Bild verschwindet*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
	},
};
	
RecMedia["ae82ddbb-8dd0-4979-9606-ffdc1877b363"] = {
	itemDisplayName = "VHS: Tronya",
	title = "Von James fuer Tronya",
	subtitle = nil,
	author = nil,
	extra = nil,
	spawning = 99,
	category = "Jazzy-VHS",
	lines = {
		{ text = "*James atmet tief ein und schaut in die Kamera*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Es faellt mir schwer, die richtigen Worte zu finden, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... jetzt wo ich nicht mehr bei dir bin.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Die Zeit, die wir gemeinsam durch die Apokalypse gegangen sind, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... war die wertvollste meines Lebens. ", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Von den ersten Tagen, als wir uns vor Riverside trafen, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... bis hin zu unseren Gespraechen ueber die Zukunft, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... hast du mir immer gezeigt, was wirklich zaehlt.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James schliesst die Augen und seufzt leise*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Ich werde nie vergessen, wie du mich mit deinem Wissen ueber Autos ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... und Mechanik beeindruckt hast, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... und wie du selbst in den schlimmsten Zeiten nie deinen Humor verloren hast.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James schaut in die Kamera, dann laechelt er schwach*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Ich erinnere mich an die Naechte, in denen wir uns gegenseitig aufgemuntert haben, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... waehrend die Welt um uns zusammenbrach.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Die Momente, in denen du mir bei meinen Verletzungen geholfen hast, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... oder wir den Ausbau unserer Villa geplant haben.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James holt tief Luft*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Du bist eine unglaubliche Frau, Tronya.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Du wirst immer in der Lage sein, weiterzumachen, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... so wie du es immer getan hast ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... stark, mutig und unaufhaltsam.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*Mit zitternden Haenden greift er nach einem Bilderbuch und haelt es fest*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Der Antrag, unsere Hochzeit und die Geburt von Jules ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... waren die schoensten Momente meines Lebens, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... die ich immer in meinem Herzen tragen werde.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Jules wird die Zukunft mit deiner Staerke und Liebe gestalten, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... und durch ihn werde ich immer bei dir sein, egal wie weit die Zeit uns trennt.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James wischt sich eine Traene aus dem Gesicht und atmet tief durch*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Ich moechte, dass du weisst, wie tief meine Gefuehle fuer dich waren.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "Du bist nicht nur die, mit der ich diese Reise gemacht habe, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... sondern auch die, die mich immer wieder daran erinnert hat, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... was es bedeutet, lebendig zu sein, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... selbst wenn alles andere verloren scheint.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James schliesst die Augen und atmet tief ein*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Pass gut auf dich und Jules auf, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... und wenn der Tag kommt, an dem du dich wieder sicher fuehlst, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... dann hoffe ich, dass du weiterkaempfst und niemals vergisst, ...", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "... was wir gemeinsam hatten.", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*James schluckt hart und seine Augen fuellen sich mit Traenen*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
		{ text = "Ich liebe dich Tronya!", r = 0.20, g = 0.60, b = 0.40, codes = "" },
		{ text = "*Das Bild verschwindet*", r = 0.50, g = 0.50, b = 0.50, codes = "" },
	},
};
